# Generates the export-forwarding sources for a pinned module export surface.
#
# Run in CMake script mode with:
#   MANIFEST        pinned export manifest
#   OUT_DIR         directory that receives the generated sources
#   PREFIX          file and symbol prefix, for example `winmm`
#   BACKEND_MODULE  module name used by the self-forward negative control
#
# Emitted artifacts:
#   <prefix>_export_table.cpp       the pinned surface as data
#   <prefix>_proxy.def              full ordinal/name/NONAME export surface
#   <prefix>_proxy_thunks.cpp       one naked x86 thunk per entry
#   <prefix>_backend_contract.hpp   synthetic backend call contract
#   <prefix>_backend.def            same surface, aliases preserved
#   <prefix>_backend.cpp            one synthetic implementation per entry point
#   <prefix>_selfforward.def        `.def` forwarders back to BACKEND_MODULE
#   <prefix>_selfforward.cpp        anchor translation unit for the control

cmake_minimum_required(VERSION 3.25)

foreach(required IN ITEMS MANIFEST OUT_DIR PREFIX BACKEND_MODULE)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "GenerateExportForwarder.cmake requires -D${required}=<value>")
  endif()
endforeach()

file(STRINGS "${MANIFEST}" manifest_lines)

set(ordinals "")
set(names "")
set(aliases "")
foreach(line IN LISTS manifest_lines)
  string(STRIP "${line}" line)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()

  string(REGEX MATCHALL "[^ \t]+" fields "${line}")
  list(LENGTH fields field_count)
  if(field_count LESS 2 OR field_count GREATER 3)
    message(FATAL_ERROR "malformed manifest entry: ${line}")
  endif()

  list(GET fields 0 ordinal)
  list(GET fields 1 name)
  if(NOT ordinal MATCHES "^[0-9]+$")
    message(FATAL_ERROR "malformed manifest ordinal: ${line}")
  endif()
  if(NOT name STREQUAL "-" AND NOT name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "malformed manifest export name: ${line}")
  endif()

  set(alias 0)
  if(field_count EQUAL 3)
    list(GET fields 2 alias_field)
    if(NOT alias_field MATCHES "^=([0-9]+)$")
      message(FATAL_ERROR "malformed manifest alias: ${line}")
    endif()
    set(alias "${CMAKE_MATCH_1}")
  endif()

  if(ordinal IN_LIST ordinals)
    message(FATAL_ERROR "duplicate manifest ordinal: ${ordinal}")
  endif()

  list(APPEND ordinals "${ordinal}")
  list(APPEND names "${name}")
  list(APPEND aliases "${alias}")
endforeach()

list(LENGTH ordinals entry_count)
if(entry_count EQUAL 0)
  message(FATAL_ERROR "manifest ${MANIFEST} declares no exports")
endif()

list(GET ordinals 0 ordinal_base)
set(name_count 0)
foreach(name IN LISTS names)
  if(NOT name STREQUAL "-")
    math(EXPR name_count "${name_count} + 1")
  endif()
endforeach()

foreach(alias IN LISTS aliases)
  if(NOT alias EQUAL 0 AND NOT alias IN_LIST ordinals)
    message(FATAL_ERROR "manifest alias target ${alias} is not an exported ordinal")
  endif()
endforeach()

set(symbol_prefix "ncm_${PREFIX}")
set(generated_banner "// Generated by cmake/GenerateExportForwarder.cmake from ${MANIFEST}.\n// Do not edit; change the manifest instead.\n")

set(export_table "${generated_banner}\n#include \"ncm/winmm_proxy/forwarder.hpp\"\n\nnamespace ncm::winmm_proxy {\nnamespace {\n\nconstexpr export_entry table[] = {\n")
set(proxy_def "; ${entry_count} entries generated from ${MANIFEST}.\nEXPORTS\n")
set(thunks "${generated_banner}\n#include \"ncm/winmm_proxy/forwarder.hpp\"\n\n// Each thunk is a bare x86 dispatch, so it must not acquire a compiler-managed\n// frame; `pushad`/`popad` around the one-time resolver restores every register.\n#pragma warning(disable : 4731)\n\nextern \"C\" {\n\nstatic void* ${symbol_prefix}_targets[${entry_count}];\nstatic long ${symbol_prefix}_resolved;\n\nvoid __cdecl ${symbol_prefix}_resolve(void) {\n  ncm::winmm_proxy::resolve_backend(\n      &${symbol_prefix}_resolved, ${symbol_prefix}_targets, ${entry_count});\n}\n")
set(backend_def "; ${entry_count} entries generated from ${MANIFEST}.\nEXPORTS\n")
set(backend_impl "${generated_banner}\n#include \"${PREFIX}_backend_contract.hpp\"\n\nextern \"C\" {\n")
set(selfforward_def "; ${entry_count} entries generated from ${MANIFEST}.\nEXPORTS\n")

set(index 0)
foreach(ordinal IN LISTS ordinals)
  list(GET names ${index} name)
  list(GET aliases ${index} alias)
  math(EXPR offset "${index} * 4")

  set(entry_point "${ordinal}")
  if(NOT alias EQUAL 0)
    set(entry_point "${alias}")
  endif()

  if(name STREQUAL "-")
    string(APPEND export_table "    {${ordinal}, nullptr, ${alias}},\n")
    string(APPEND proxy_def "    ${symbol_prefix}_thunk_${ordinal} @${ordinal} NONAME\n")
    string(APPEND backend_def "    ${symbol_prefix}_backend_${entry_point} @${ordinal} NONAME\n")
    # `link.exe` resolves a `.def` forwarder target through an import library,
    # which is keyed by name. An unnamed ordinal has no such key, so ordinal
    # ${ordinal} cannot be expressed as a forwarder at all.
    string(APPEND selfforward_def
           "; ordinal ${ordinal} is unnamed and cannot be expressed as a `.def` forwarder\n")
  else()
    string(APPEND export_table "    {${ordinal}, \"${name}\", ${alias}},\n")
    string(APPEND proxy_def "    ${name}=${symbol_prefix}_thunk_${ordinal} @${ordinal}\n")
    string(APPEND backend_def "    ${name}=${symbol_prefix}_backend_${entry_point} @${ordinal}\n")
    string(APPEND selfforward_def "    ${name}=${BACKEND_MODULE}.${name} @${ordinal}\n")
  endif()

  string(APPEND thunks
         "\n__declspec(naked) void __cdecl ${symbol_prefix}_thunk_${ordinal}(void) {\n"
         "  __asm {\n"
         "    cmp dword ptr [${symbol_prefix}_resolved], 0\n"
         "    jne ncm_forward\n"
         "    pushfd\n"
         "    pushad\n"
         "    call ${symbol_prefix}_resolve\n"
         "    popad\n"
         "    popfd\n"
         "  ncm_forward:\n"
         "    jmp dword ptr [${symbol_prefix}_targets + ${offset}]\n"
         "  }\n}\n")

  if(alias EQUAL 0)
    string(APPEND backend_impl
           "\nunsigned long __stdcall ${symbol_prefix}_backend_${ordinal}(\n"
           "    unsigned long first, unsigned long second, unsigned long third, unsigned long fourth) {\n"
           "  return ncm::winmm_proxy_fixture::expected_result(\n"
           "      ${ordinal}, first, second, third, fourth);\n}\n")
  endif()

  math(EXPR index "${index} + 1")
endforeach()

string(APPEND export_table
       "};\n\nstatic_assert(sizeof(table) / sizeof(table[0]) == ${entry_count}, \"export table size drifted\");\n\n"
       "}  // namespace\n\n"
       "const export_entry* pinned_exports(unsigned* count) noexcept {\n"
       "  if (count != nullptr) {\n    *count = ${entry_count};\n  }\n  return table;\n}\n\n"
       "surface_shape pinned_shape() noexcept {\n"
       "  return {${ordinal_base}, ${entry_count}, ${name_count}};\n}\n\n"
       "}  // namespace ncm::winmm_proxy\n")
string(APPEND thunks "\n}  // extern \"C\"\n")
string(APPEND backend_impl "\n}  // extern \"C\"\n")

set(backend_contract "${generated_banner}\n#pragma once\n\nnamespace ncm::winmm_proxy_fixture {\n\n// Every synthetic backend export returns this value, so a call that arrives\n// through a proxy proves both that it reached the backend and which entry\n// point it reached, and that the x86 stdcall arguments survived the thunk.\nconstexpr unsigned long expected_result(\n    unsigned long ordinal, unsigned long first, unsigned long second,\n    unsigned long third, unsigned long fourth) noexcept {\n  return ordinal * 2654435761UL + first * 3UL + second * 5UL + third * 7UL +\n      fourth * 11UL;\n}\n\nconstexpr unsigned long entry_count = ${entry_count};\n\n}  // namespace ncm::winmm_proxy_fixture\n")

set(selfforward_impl "${generated_banner}\n#include <Windows.h>\n\n// The negative control exports nothing of its own; every entry in its `.def`\n// is a name-resolved forwarder to `${BACKEND_MODULE}`.\nBOOL APIENTRY DllMain(HMODULE, DWORD, LPVOID) {\n  return TRUE;\n}\n")

file(WRITE "${OUT_DIR}/${PREFIX}_export_table.cpp" "${export_table}")
file(WRITE "${OUT_DIR}/${PREFIX}_proxy.def" "${proxy_def}")
file(WRITE "${OUT_DIR}/${PREFIX}_proxy_thunks.cpp" "${thunks}")
file(WRITE "${OUT_DIR}/${PREFIX}_backend_contract.hpp" "${backend_contract}")
file(WRITE "${OUT_DIR}/${PREFIX}_backend.def" "${backend_def}")
file(WRITE "${OUT_DIR}/${PREFIX}_backend.cpp" "${backend_impl}")
file(WRITE "${OUT_DIR}/${PREFIX}_selfforward.def" "${selfforward_def}")
file(WRITE "${OUT_DIR}/${PREFIX}_selfforward.cpp" "${selfforward_impl}")
